# Generated by Django 2.0.13 on 2019-03-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
