# Generated by Django 2.0.13 on 2019-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.TextField(max_length=50000, null=True),
        ),
    ]
